### ISSUE TITLE
交易所无法交易

### ISSUE THREAD

**Issue by pruly** [superbts/SuperONE#3]
用鼓鼓钱包账号的私钥导入的账号，交易广播失败。在确认界面提示“Transaction was not signed.Do you have a private key?[no_signers]"  转账也是一样。

**Comment by crazybits** [comment]
一个帐号有两个私钥，估计你导入的是owner private key，你应该导入active private key，这个才是真正用来签发交易的。

**Comment by pruly** [comment]
按照你说的导入，已经解决了。谢谢

**Comment by purplieee** [comment]
我用过优盾钱包进行交易，没出现无法交易的问题
